### PR TITLE
largest-series-product corner cases

### PR DESCRIPTION
**Pull request by petertseng**
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.

### CODE REVIEW

**Comment by petertseng** [comment]
That's what I get for trying to write tests without subsequently running them.

(I admit I'm writing these tests without so much as even installing LFE...!)

going to use `is-error`, should be good now.

**Comment by petertseng** [comment]
@yurrriq  don't forget! Although I'm not too rushed, since http://exercism.io/stats/lfe shows we're not letting too many submissions go by with the old tests. But just want to get this out of my queue at some point.

**Comment by yurrriq** [comment]
Yikes! Thanks for the ping, @petertseng. I'll take a look shortly.

**Comment by yurrriq** [comment]
Looks good to me and Travis is pleased. Thanks for this, and for your patience.

**Comment by petertseng** [comment]
And thank you!

**Pull request merged**
